
# DataSource Config
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&&serverTimezone=UTC
    username: root
    password: 12345678
shiro-redis:
  enabled: true
  redis-mapper:
    host: 127.0.0.1:6379
markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长 7天 单位秒
    expire: 604800
    header: token
mybatis-plus:
  mapper-locations: classpath*:mapper/**Mapper.xml
